"""
routers/growers.py

Feature 5 — Grower Profile Intelligence per tehsil
"""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import text
from sqlalchemy.orm import Session
from typing import Optional

from database import get_db
from services.scoring import get_grower_intelligence
from services.campaign import generate_tehsil_briefing, generate_whatsapp_message

router = APIRouter(prefix="/growers", tags=["Growers"])


@router.get("/tehsil/{tehsil}")
def grower_intelligence(
    tehsil: str,
    db: Session = Depends(get_db),
):
    """
    Feature 5: Returns a rich intelligence card for all growers in a tehsil.

    Includes:
    - Demographics (farm size, age, gender split)
    - Crop breakdown and current growth stages
    - Warm leads (product scanners + offline event attendees)
    - WhatsApp engagement stats
    - Language distribution
    """
    intel = get_grower_intelligence(db, tehsil=tehsil)

    if not intel.get("summary", {}).get("total_growers"):
        raise HTTPException(status_code=404, detail=f"No growers found in tehsil: {tehsil}")

    return intel


@router.get("/tehsil/{tehsil}/briefing")
def tehsil_briefing(
    tehsil: str,
    db: Session = Depends(get_db),
):
    """
    Feature 5 + AI: Returns a natural-language briefing for a rep
    about to visit a tehsil, generated by Claude.
    """
    intel = get_grower_intelligence(db, tehsil=tehsil)

    if not intel.get("summary", {}).get("total_growers"):
        raise HTTPException(status_code=404, detail=f"No growers found in tehsil: {tehsil}")

    briefing = generate_tehsil_briefing(intel)

    return {
        "tehsil": tehsil,
        "briefing": briefing,
        "data_summary": intel.get("summary"),
        "upcoming_crop_stages": intel.get("upcoming_crop_stages"),
        "warm_lead_count": len(intel.get("warm_leads", [])),
    }


@router.get("/tehsil/{tehsil}/whatsapp-message")
def preview_whatsapp_message(
    tehsil: str,
    db: Session = Depends(get_db),
):
    """
    Generates a sample WhatsApp message for the dominant crop
    and current growth stage in a tehsil.
    Useful for campaign preview.
    """
    intel = get_grower_intelligence(db, tehsil=tehsil)
    crops = intel.get("crop_breakdown", [])
    stages = intel.get("upcoming_crop_stages", {})
    languages = intel.get("language_breakdown", [])

    if not crops:
        raise HTTPException(status_code=404, detail="No crop data for this tehsil.")

    dominant_crop = crops[0]["crop"]
    dominant_language = languages[0]["language"] if languages else "Hindi"
    stage_info = stages.get(dominant_crop)

    if not stage_info:
        stage = "growing"
    else:
        stage = stage_info["stage"]

    # Pick a product relevant to this crop+stage
    from services.campaign import STAGE_PRODUCT_MAP, PRODUCT_CROP_MAP
    candidate_products = STAGE_PRODUCT_MAP.get(stage, [])
    if not candidate_products:
        candidate_products = [
            p for p, c in PRODUCT_CROP_MAP.items()
            if c == dominant_crop or c == "multiple"
        ][:2]

    product = candidate_products[0] if candidate_products else "Syngenta crop protection"

    message = generate_whatsapp_message(
        crop=dominant_crop,
        stage=stage,
        product=product,
        language=dominant_language,
    )

    return {
        "tehsil": tehsil,
        "dominant_crop": dominant_crop,
        "stage": stage,
        "product": product,
        "language": dominant_language,
        "whatsapp_message": message,
    }


@router.get("/list-tehsils")
def list_tehsils(
    state: Optional[str] = Query(default=None),
    db: Session = Depends(get_db),
):
    """Lists all tehsils that have grower data. Useful for dropdowns in the UI."""
    q = "SELECT DISTINCT tehsil, district, state FROM growers"
    params = {}
    if state:
        q += " WHERE state = :state"
        params["state"] = state
    q += " ORDER BY state, district, tehsil"

    rows = db.execute(text(q), params).mappings().all()
    return {
        "total": len(rows),
        "tehsils": [dict(r) for r in rows],
    }
